//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationOSSBSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataConnectionSubscriber
    {
        public int IdConnection { get; set; }
        public int NumberPort { get; set; }
        public int IdTypePort { get; set; }
        public int IdPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
