//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationOSSBSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationInstalledEquipment
    {
        public int IdInstalledEquipment { get; set; }
        public int IdTypeEquipmentData { get; set; }
        public int idIdentificationData { get; set; }
        public int idTypePort { get; set; }
        public int NumberPorts { get; set; }
        public int IdInstallationInformation { get; set; }
        public string OtherInformation { get; set; }
    
        public virtual EquipmentData EquipmentData { get; set; }
        public virtual IdentificationData IdentificationData { get; set; }
        public virtual InstallationPlaceInformation InstallationPlaceInformation { get; set; }
        public virtual TypesPort TypesPort { get; set; }
    }
}
