//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationOSSBSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.DataConnectionSubscribers = new HashSet<DataConnectionSubscriber>();
        }
    
        public int IdPerson { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Patronimic { get; set; }
        public int IdRole { get; set; }
        public int IdUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataConnectionSubscriber> DataConnectionSubscribers { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
