//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationOSSBSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesPort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypesPort()
        {
            this.InformationInstalledEquipments = new HashSet<InformationInstalledEquipment>();
        }
    
        public int IdTypePort { get; set; }
        public string TypePort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformationInstalledEquipment> InformationInstalledEquipments { get; set; }
    }
}
